In [2]:
!pip install transformers

Requirement already satisfied: transformers in c:\users\asus\anaconda3\lib\site-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (1.21.0)
Requirement already satisfied: numpy>=1.17 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\asus\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\asus\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\asus\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\asus\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

In [3]:
!pip install "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\users\asus\anaconda3\lib\site-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (1.21.0)
Requirement already satisfied: numpy>=1.17 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (2.11.0+cu128)
Requirement already satisfied: accelerate>=1.1.0 in c:\users\asus\anaconda3\lib\site-packages (from transformers[torch]) (1.14.0)
Requirement already satisfied: click>=8.4.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\asus\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: anyio in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.10.0)
Requirement already satisfied: certifi in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\asus\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers[torch]) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\asus\anaconda3\lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: psutil in c:\users\asus\anaconda3\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.0.0)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Requirement already satisfied: setuptools<82 in c:\users\asus\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\asus\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\asus\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.5)
Requirement already satisfied: jinja2 in c:\users\asus\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\asus\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\asus\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)

In [4]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [5]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [6]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [7]:
train_data["dialogue"][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [8]:
train_data.sample(5)

,id,dialogue,summary
6981,13827927,Ashlyn: he is a nice person with a cute cat\r\...,Ashlyn found the Instagram account of Rowan We...
4688,13813382,Jason: What time is the breakfast?\r\nLaura: 7...,Breakfast is served 7:30-11:00.
4938,13680399,"Paul: Hey, did you buy the food for tomorrow?\...",John has stocked up on beer for tomorrow. Paul...
13896,13611517,"Misha: Momma, does god see us all the time?\r\...",Misha asks her mother a number of questions ab...
3758,13716722-1,"Dave: Guys! The weather is great, I'm going fo...","Cathy, Fiona and Isma will pick Ismael up with..."

In [9]:
print(train_data.shape)
print(val_data.shape)

(14732, 3)
(818, 3)

In [10]:
#random sampling
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True) # removes the old index instead of adding it as a new column

In [11]:
train_data.shape

(4000, 3)

## Data_Preprocessing

Regex (Regular Expression) is a pattern used to search, match, or replace text.
It helps find specific words, numbers, symbols, or formats in a string.
It is commonly used for text preprocessing, validation, and data cleaning.
Example: r"\d+" finds all numbers, and r"http\S+" removes URLs.
 # sub is equal to substitutions

In [12]:
import re # Regular Expression (RegEx)
def clean_data(text):
    text = re.sub(r"\r\n", " ", text) # lines
    text = re.sub(r"\s+", " ", text) # space
    text = re.sub(r"<.*?>", " ", text) # html tags
    text = text.strip().lower()
    return text

In [13]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [14]:
train_data["dialogue"][0]

"violet: hi! i came across this austin's article and i thought that you might find it interesting violet:   claire: hi! :) thanks, but i've already read it. :) claire: but thanks for thinking about me :)"

## Tokenization

In [15]:
tokenizer = T5Tokenizer.from_pretrained("t5-small") # t5_small is the light weight model

In [16]:
# row data => tokenized for fine-tuning
def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length=512, truncation=True)
    targets = tokenizer(data["summary"], padding="max_length", max_length=150, truncation=True)
    inputs["labels"] = targets["input_ids"] # token ids => add to input as labels
    return inputs

''' 
Dialogue → Input Tokens
Summary → Label Tokens
↓
Return both for Transformer fine-tuning.
'''

' \nDialogue → Input Tokens\nSummary → Label Tokens\n↓\nReturn both for Transformer fine-tuning.\n'

Dialogue Tokens
        ↓
 Transformer
        ↓
Predicted Tokens
        ↓
Compare with
Target Tokens (Labels)
        ↓
Loss
        ↓
Backpropagation
*---------------------------------------------------------------------*
Dialogue → Input Tokens → Model → Predicted Tokens
Summary → Label Tokens ────────────────▲
                                       │
                               Loss is calculated here

In [17]:
train_dataset = train_data.apply(tokenize, axis=1).tolist() # tolist is compatible with the huggingface transformers 
val_dataset = val_data.apply(tokenize, axis=1).tolist()

In [18]:
train_dataset[0]

{'input_ids': [25208, 10, 7102, 55, 3, 23, 764, 640, 48, 403, 17, 77, 31, 7, 1108, 11, 3, 23, 816, 24, 25, 429, 253, 34, 1477, 25208, 10, 3, 7997, 15, 10, 7102, 55, 3, 10, 61, 2049, 6, 68, 3, 23, 31, 162, 641, 608, 34, 5, 3, 10, 61, 3, 7997, 15, 10, 68, 2049, 21, 1631, 81, 140, 3, 10, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [25208, 1622, 3, 7997, 15, 403, 17, 77, 31, 7, 1108, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [19]:
# input ids => dialogue => token ids
# 1 => End of sequence, remaining zeros are padding
# attention mask - 1 means valid tokens and 0 means padding
# labels - target => summary token

In [20]:
print(len(train_dataset[0]['input_ids']))
print(len(train_dataset[0]['labels']))

512
150

In [21]:
type(train_dataset)

list

## Working with our model

In [22]:
# NLP - Generation Task 
model = T5ForConditionalGeneration.from_pretrained("t5-small")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [23]:
# fine - tunning
import torch
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("device: ", device)
model.to(device)

device:  cuda

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [24]:
# training aarguments
training_args = TrainingArguments(
    output_dir = "./results",
    num_train_epochs=6,
    weight_decay=0.01,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",# when to validate model -> after one epoch
    save_strategy="epoch",
    warmup_steps=500
    # zero to default learning_rate in 500 steps
)

weight_decay=0.01 => tells the optimizer to slightly decrease the weights after every update, helping the model learn more generalized patterns instead of memorizing the training data.

In [25]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = val_dataset
)

In [26]:
# Train the model
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3000, training_loss=0.9117616933186848, metrics={'train_runtime': 2558.5567, 'train_samples_per_second': 9.38, 'train_steps_per_second': 1.173, 'total_flos': 3248203235328000.0, 'train_loss': 0.9117616933186848, 'epoch': 6.0})

In [27]:
# model load => fine-tune => save model : this is the same for all hugging face model

In [29]:
model.save_pretrained("./saved_summary_model")
tokenizer.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./saved_summary_model\\tokenizer_config.json',
 './saved_summary_model\\tokenizer.json')

In [33]:
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

## Test the core logic for summarization

In [41]:
def summarize_dialogue(dialogue):
    dialogue = clean_data(dialogue) # clean
    
    #tokenize
    inputs = tokenizer(
        dialogue,
        padding="max_length",
        max_length=512,
        truncation=True,
        return_tensors="pt"
    ).to(device)
    #generate the summary => token ids
    model.to(device)
    targets = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=150,
        num_beams=4, # transformer will generate an sequence of 4 outputs and will provide best one among this all 
        early_stopping=True # When we get end of sequence then the model should stop and return the best among this all
    )
    #token ids convert to summary => decoding
    summary = tokenizer.decode(targets[0], skip_special_tokens=True) # will skip tokens like EOS etc
    return summary

In [ ]:
test_dialogue = """
Reporter: In today's technology news, artificial intelligence continues to expand rapidly across industries, from healthcare to finance and education. Recent reports suggest that AI adoption has significantly increased over the past few years.

Reporter: Companies are investing heavily in machine learning systems to automate tasks, improve decision-making, and enhance customer experiences. However, this growth has also raised questions about job displacement and ethical concerns.

Expert: AI systems are becoming more capable due to advances in deep learning and access to large datasets. These models can now perform complex tasks such as language understanding, image recognition, and even code generation.

Expert: At the same time, there are valid concerns about bias in AI models, as they often reflect the data they are trained on. Ensuring fairness and transparency is becoming a key area of research.

Reporter: Governments and organizations are beginning to introduce regulations to guide the development and deployment of AI technologies. The goal is to balance innovation with accountability.

Expert: Another challenge is explainability. Many modern AI systems, especially deep neural networks, operate as “black boxes,” making it difficult to understand how decisions are made.

Reporter: Experts also highlight the importance of responsible AI development, including data privacy, security, and long-term societal impact.

Expert: Looking ahead, collaboration between researchers, policymakers, and industry leaders will be crucial to ensure that AI systems are developed and used in a safe and beneficial way.
"""

summary = summarize_dialogue(test_dialogue)
print("Summary: ", summary)

In [28]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
print(torch.cuda.device_count())

2.11.0+cu128
12.8
True
NVIDIA GeForce RTX 3050 Laptop GPU
1